# Generated by Django 4.0.5 on 2024-01-11 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0002_usermember_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermember',
            name='course',
        ),
    ]
