# Generated by Django 4.0.5 on 2022-06-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0003_usermember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermember',
            name='image',
            field=models.ImageField(blank=True, default='default1.jpg', null=True, upload_to='image/'),
        ),
    ]
