# Generated by Django 4.0.5 on 2023-02-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0004_alter_usermember_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_age',
            field=models.IntegerField(default=0),
        ),
    ]
